# Generated by Django 5.0.6 on 2024-06-03 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_product_category_remove_order_product_and_more'),
    ]

    operations = [
    ]
